import {
  Wifi,
  Waves,
  Dumbbell,
  Car,
  PawPrint,
  Tv,
  Thermometer,
  Cigarette,
  Cable,
  Maximize,
  Bath,
  Phone,
  Sprout,
  Hammer,
  Bus,
  Mountain,
  VolumeX,
  Home,
  Warehouse,
  Building,
  Castle,
  Trees,
  Tent,
  Ship,
  Factory,
  Hotel,
  School,
  Store,
  Utensils,
  Coffee,
  Snowflake,
  Sun,
  Accessibility,
  Key,
  AlarmClock,
  Fence,
  Lamp,
  ShowerHead,
  Leaf,
  Bike,
  LucideIcon,
  Cross,
  Cpu,
  Fuel,
  Package,
  Monitor,
  Signal,
  CookingPot,
  FlaskConical,
  Droplet,
  Cannabis,
} from "lucide-react";

// Enhanced Amenity Enum
export enum AmenityEnum {
  // Existing
  WasherDryer = "WasherDryer",
  AirConditioning = "AirConditioning",
  Dishwasher = "Dishwasher",
  HighSpeedInternet = "HighSpeedInternet",
  HardwoodFloors = "HardwoodFloors",
  WalkInClosets = "WalkInClosets",
  Microwave = "Microwave",
  Refrigerator = "Refrigerator",
  Pool = "Pool",
  Gym = "Gym",
  Parking = "Parking",
  PetsAllowed = "PetsAllowed",
  WiFi = "WiFi",

  // New additions
  Balcony = "Balcony",
  Garden = "Garden",
  Terrace = "Terrace",
  Fireplace = "Fireplace",
  Elevator = "Elevator",
  Doorman = "Doorman",
  SecuritySystem = "SecuritySystem",
  SmartHome = "SmartHome",
  Furnished = "Furnished",
  WheelchairAccess = "WheelchairAccess",
  BikeStorage = "BikeStorage",
  EVCharging = "EVCharging",
  LaundryRoom = "LaundryRoom",
  Storage = "Storage",
  CentralHeating = "CentralHeating",
  SolarPanels = "SolarPanels",
  GreenSpace = "GreenSpace",
  Concierge = "Concierge",
  BreakfastIncluded = "BreakfastIncluded",
  CleaningService = "CleaningService",
}

export const AmenityIcons: Record<AmenityEnum, LucideIcon> = {
  // Existing
  WasherDryer: Waves,
  AirConditioning: Thermometer,
  Dishwasher: Waves,
  HighSpeedInternet: Wifi,
  HardwoodFloors: Home,
  WalkInClosets: Maximize,
  Microwave: Utensils,
  Refrigerator: Thermometer,
  Pool: Waves,
  Gym: Dumbbell,
  Parking: Car,
  PetsAllowed: PawPrint,
  WiFi: Wifi,

  // New
  Balcony: Sun,
  Garden: Sprout,
  Terrace: Sun,
  Fireplace: Sun,
  Elevator: Maximize,
  Doorman: Key,
  SecuritySystem: AlarmClock,
  SmartHome: Home,
  Furnished: Lamp,
  WheelchairAccess: Accessibility,
  BikeStorage: Bike,
  EVCharging: Car,
  LaundryRoom: Waves,
  Storage: Warehouse,
  CentralHeating: Thermometer,
  SolarPanels: Sun,
  GreenSpace: Leaf,
  Concierge: Key,
  BreakfastIncluded: Coffee,
  CleaningService: ShowerHead,
};

// Enhanced Highlight Enum
export enum HighlightEnum {
  // Existing
  HighSpeedInternetAccess = "HighSpeedInternetAccess",
  WasherDryer = "WasherDryer",
  AirConditioning = "AirConditioning",
  Heating = "Heating",
  SmokeFree = "SmokeFree",
  CableReady = "CableReady",
  SatelliteTV = "SatelliteTV",
  DoubleVanities = "DoubleVanities",
  TubShower = "TubShower",
  Intercom = "Intercom",
  SprinklerSystem = "SprinklerSystem",
  RecentlyRenovated = "RecentlyRenovated",
  CloseToTransit = "CloseToTransit",
  GreatView = "GreatView",
  QuietNeighborhood = "QuietNeighborhood",

  // New additions
  Waterfront = "Waterfront",
  MountainView = "MountainView",
  CityView = "CityView",
  HistoricBuilding = "HistoricBuilding",
  NewConstruction = "NewConstruction",
  EnergyEfficient = "EnergyEfficient",
  SmartTechnology = "SmartTechnology",
  PetFriendly = "PetFriendly",
  ChildFriendly = "ChildFriendly",
  SeniorFriendly = "SeniorFriendly",
  LuxuryFinishes = "LuxuryFinishes",
  OpenConcept = "OpenConcept",
  HighCeilings = "HighCeilings",
  NaturalLight = "NaturalLight",
  PrivateOutdoorSpace = "PrivateOutdoorSpace",
  WalkableArea = "WalkableArea",
  BikeFriendly = "BikeFriendly",
}

export const HighlightIcons: Record<HighlightEnum, LucideIcon> = {
  // Existing
  HighSpeedInternetAccess: Wifi,
  WasherDryer: Waves,
  AirConditioning: Thermometer,
  Heating: Thermometer,
  SmokeFree: Cigarette,
  CableReady: Cable,
  SatelliteTV: Tv,
  DoubleVanities: Maximize,
  TubShower: Bath,
  Intercom: Phone,
  SprinklerSystem: Sprout,
  RecentlyRenovated: Hammer,
  CloseToTransit: Bus,
  GreatView: Mountain,
  QuietNeighborhood: VolumeX,

  // New
  Waterfront: Waves,
  MountainView: Mountain,
  CityView: Building,
  HistoricBuilding: Castle,
  NewConstruction: Hammer,
  EnergyEfficient: Leaf,
  SmartTechnology: Home,
  PetFriendly: PawPrint,
  ChildFriendly: School,
  SeniorFriendly: Accessibility,
  LuxuryFinishes: Castle,
  OpenConcept: Maximize,
  HighCeilings: Maximize,
  NaturalLight: Sun,
  PrivateOutdoorSpace: Trees,
  WalkableArea: Bus,
  BikeFriendly: Bike,
};

// Enhanced Property Type Enum
export enum PropertyTypeEnum {
  // Existing
  Rooms = "Rooms",
  Tinyhouse = "Tinyhouse",
  Apartment = "Apartment",
  Villa = "Villa",
  Townhouse = "Townhouse",
  Cottage = "Cottage",

  Studio = "Studio",
  Loft = "Loft",
  Condo = "Condo",
  Bungalow = "Bungalow",
  Cabin = "Cabin",
  Chalet = "Chalet",
  Farmhouse = "Farmhouse",
  Houseboat = "Houseboat",
  RV = "RV",
  Camper = "Camper",
  MobileHome = "MobileHome",
  Duplex = "Duplex",
  Triplex = "Triplex",
  Penthouse = "Penthouse",
  Mansion = "Mansion",
  Castle = "Castle",
  SharedHouse = "SharedHouse",
  CoLiving = "CoLiving",
  StudentHousing = "StudentHousing",
  SeniorHousing = "SeniorHousing",
  ServicedApartment = "ServicedApartment",
  BoutiqueHotel = "BoutiqueHotel",

  OfficeSpace = "OfficeSpace",
  CoworkingSpace = "CoworkingSpace",
  RetailStore = "RetailStore",
  RestaurantSpace = "RestaurantSpace",
  Warehouse = "Warehouse",
  MedicalOffice = "MedicalOffice",
  IndustrialFlex = "IndustrialFlex",
  DataCenter = "DataCenter",
  ColdStorage = "ColdStorage",
  Showroom = "Showroom",
  GasStation = "GasStation",
  SelfStorage = "SelfStorage",
  ParkingLot = "ParkingLot",
  Hotel = "Hotel",
  Billboard = "Billboard",
  CellTower = "CellTower",
  AgriculturalLand = "AgriculturalLand",
  DarkKitchen = "DarkKitchen",
  LabSpace = "LabSpace",
  Cleanroom = "Cleanroom",
}

export const PropertyTypeIcons: Record<PropertyTypeEnum, LucideIcon> = {
  // Existing
  Rooms: Home,
  Tinyhouse: Warehouse,
  Apartment: Building,
  Villa: Castle,
  Townhouse: Home,
  Cottage: Trees,

  // New
  Studio: Home,
  Loft: Building,
  Condo: Building,
  Bungalow: Home,
  Cabin: Trees,
  Chalet: Home,
  Farmhouse: Home,
  Houseboat: Ship,
  RV: Car,
  Camper: Tent,
  MobileHome: Factory,
  Duplex: Home,
  Triplex: Home,
  Penthouse: Building,
  Mansion: Castle,
  Castle: Castle,
  SharedHouse: Home,
  CoLiving: Hotel,
  StudentHousing: School,
  SeniorHousing: Accessibility,
  ServicedApartment: Hotel,
  BoutiqueHotel: Hotel,
  OfficeSpace: Building,
  CoworkingSpace: Home,
  RetailStore: Store,
  RestaurantSpace: Utensils,
  Warehouse: Warehouse,
  MedicalOffice: Cross, // Need to import
  IndustrialFlex: Factory,
  DataCenter: Cpu, // Need to import
  ColdStorage: Snowflake,
  Showroom: Store,
  GasStation: Fuel, // Need to import
  SelfStorage: Package, // Need to import
  ParkingLot: Car,
  Hotel: Hotel,
  Billboard: Monitor, // Need to import
  CellTower: Signal, // Need to import
  AgriculturalLand: Sprout,
  DarkKitchen: CookingPot, // Need to import
  LabSpace: FlaskConical, // Need to import
  Cleanroom: Droplet, // Need to import
};

// Categories for better filtering
export enum PropertyCategoryEnum {
  Apartment = "Apartment",
  House = "House",
  Room = "Room",
  Unique = "Unique",
  Shared = "Shared",
  Temporary = "Temporary",
}

export const PropertyCategoryIcons: Record<PropertyCategoryEnum, LucideIcon> = {
  Apartment: Building,
  House: Home,
  Room: Home,
  Unique: Castle,
  Shared: Hotel,
  Temporary: Tent,
};

export const NAVBAR_HEIGHT = 52; // in pixels
// Test users for development
export const testUsers = {
  tenant: {
    username: "Carol White",
    userId: "us-east-2:76543210-90ab-cdef-1234-567890abcdef",
    signInDetails: {
      loginId: "carol.white@example.com",
      authFlowType: "USER_SRP_AUTH",
    },
  },
  tenantRole: "tenant",
  manager: {
    username: "John Smith",
    userId: "us-east-2:12345678-90ab-cdef-1234-567890abcdef",
    signInDetails: {
      loginId: "john.smith@example.com",
      authFlowType: "USER_SRP_AUTH",
    },
  },
  managerRole: "manager",
};

export const LEGACY_PROPERTY_TYPES = [
  PropertyTypeEnum.Rooms,
  PropertyTypeEnum.Tinyhouse,
  PropertyTypeEnum.Apartment,
  PropertyTypeEnum.Villa,
  PropertyTypeEnum.Townhouse,
  PropertyTypeEnum.Cottage,
];
